# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Base VM OS configuration.
  config.vm.box = "geerlingguy/ubuntu2004"
  config.ssh.insert_key = false
  config.vm.synced_folder '.', '/vagrant', disabled: true

  # General VirtualBox VM configuration.
  config.vm.provider :virtualbox do |v|
    v.memory = 512
    v.cpus = 1
    v.linked_clone = true
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    v.customize ["modifyvm", :id, "--ioapic", "on"]
  end

  # Dev.
  config.vm.define "dev" do |dev|
    dev.vm.hostname = "dev.test"
    dev.vm.network :private_network, ip: "192.168.2.2"
  end
  # Registry.
  config.vm.define "registry" do |registry|
    registry.vm.hostname = "registry.test"
    registry.vm.network :private_network, ip: "192.168.2.3"
  end
  # Prod.
  config.vm.define "prod" do |prod|
    prod.vm.hostname = "prod.test"
    prod.vm.network :private_network, ip: "192.168.2.4"
  end

  # Ansible provisioning.
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "provision.yml"
    # ansible.become = true
    ansible.inventory_path = "inventories/vagrant/inventory"
    ansible.limit = "all"
    ansible.extra_vars = {
      ansible_user: 'vagrant',
      ansible_ssh_private_key_file: "~/.vagrant.d/insecure_private_key"
    }    
  end
end
