version: "3"

services: 
  app:
    container_name: app
    image: registry:5000/pilgrim2go/node-multistage-docker:latest
    restart: always
    environment: 
      - PORT=4002
    ports: 
      - "4002:4002"
    links:
      - mongo
  mongo:
    container_name: mongo
    image : mongo
    volumes: 
      - ./data:/data/db
    ports: 
      - "27017:27017"
    