version: '3'
services:
  # web:
  #   image: amazon/amazon-ecs-sample
  #   ports:
  #     - "80:80"
  #   logging:
  #     driver: awslogs
  #     options: 
  #       awslogs-group: ec2-tutorial
  #       awslogs-region: us-west-2
  #       awslogs-stream-prefix: web
  # ecsdemo-nodejs:
  #   image: brentley/ecsdemo-nodejs
  #   # ports:
  #   #   - "3000:3000"
  #   logging:
  #     driver: awslogs
  #     options: 
  #       awslogs-group: ecsdemo-nodejs
  #       awslogs-region: us-west-2
  #       awslogs-stream-prefix: ecsdemo-nodejs
  # ecsdemo-crystal:
  #   image: brentley/ecsdemo-crystal
  #   # ports:
  #   #   - "3000:3000"
  #   logging:
  #     driver: awslogs
  #     options: 
  #       awslogs-group: ecsdemo-crystal
  #       awslogs-region: us-west-2
  #       awslogs-stream-prefix: ecsdemo-crystal

  ecsdemo-frontend:
    environment:
      # - CRYSTAL_URL=http://ecsdemo-crystal.service:3000/crystal
      # - NODEJS_URL=http://ecsdemo-nodejs.service:3000
      - CRYSTAL_URL=http://ecsdemo-crystal.tutorial:3000/crystal
      - NODEJS_URL=http://ecsdemo-nodejs.tutorial:3000
    image: brentley/ecsdemo-frontend
    ports:
      - "3000:3000"
    logging:
      driver: awslogs
      options: 
        awslogs-group: ecsdemo-frontend
        awslogs-region: us-west-2
        awslogs-stream-prefix: ecsdemo-frontend  